# nixpacks.toml
# Configuración para desplegar monorepo (backend FastAPI + frontend React)
# con Dokploy utilizando Railway/Nixpacks.

[variables]
# Puerto de la aplicación web (FastAPI)
PORT = "8000"

# ------------------- FASES PERSONALIZADAS -------------------

# En setup instalamos Python, Node.js y pip vía Nix
[phases.setup]
nixPkgs = [
  "python311",
  "nodejs",
  "python311Packages.pip"
]

# En install usamos python -m pip para asegurarnos de usar el pip instalado en el entorno
[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "python -m pip install -r backend/requirements.txt",
  "cd frontend && npm ci --legacy-peer-deps && npm run build"
]

# --------------- COMANDOS DE INICIO -------------------------
[start]
cmd = "python -m uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT"

# --------------- ARCHIVOS ESTÁTICOS -------------------------
[static]
dir = "frontend/build"
