# nixpacks.toml
# Configuración para desplegar monorepo (backend FastAPI + frontend React)
# con Dokploy utilizando Railway/Nixpacks.

# Variables de entorno por defecto
[variables]
# Puerto de la aplicación web (FastAPI)
PORT = "8000"

# ------------------- FASES PERSONALIZADAS -------------------

# `setup` instala los paquetes de sistema necesarios.
[phases.setup]
# Paquetes de nix que necesitamos para construir python y node
nixPkgs = ["python311", "nodejs"]

# `install` instala dependencias de backend y frontend.
[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "python -m pip install -r backend/requirements.txt",
  "cd frontend && npm ci --legacy-peer-deps && npm run build"
]

# Ningún comando de build adicional es necesario (las salidas ya se crearon).

# --------------- COMANDOS DE INICIO -------------------------
[start]
# Servir FastAPI (backend)
cmd = "python -m uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT"

# --------------- ARCHIVOS ESTÁTICOS -------------------------
# Indica a Dokploy que la carpeta build contiene el frontend estático.
[static]
dir = "frontend/build"
