# nixpacks.toml
# Configuración para desplegar monorepo (backend FastAPI + frontend React)
# con Dokploy utilizando Railway/Nixpacks.

[variables]
# Puerto de la aplicación web (FastAPI)
PORT = "8000"

# ------------------- FASES PERSONALIZADAS -------------------

# En setup instalamos Python (con pip), Node.js y sus dependencias básicas.
[phases.setup]
nixPkgs = [
  "python311Full",   # Incluye el ejecutable pip en el perfil
  "nodejs"
]

# En install primero bootstrapeamos pip y luego instalamos dependencias.
[phases.install]
cmds = [
  # Asegurarnos de que el módulo pip está disponible
  "python -m ensurepip --upgrade",
  # Ahora ya podemos usar pip
  "python -m pip install --upgrade pip",
  "python -m pip install -r backend/requirements.txt",
  "cd frontend && npm ci --legacy-peer-deps && npm run build"
]

# --------------- COMANDOS DE INICIO -------------------------
[start]
cmd = "python -m uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT"

# --------------- ARCHIVOS ESTÁTICOS -------------------------
[static]
dir = "frontend/build"
